version: '2'
services:
  janusgraph:
    image: n0stack/janusgraph-gremlin
    build: .
    command:
      - dockerize
      - -wait
      - tcp://elasticsearch:9200
      - -timeout
      - 30s
      - bin/gremlin-server.sh
    ports:
      - "8182:8182"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
